import Head from "next/head";
import { ListCoins } from "../components/mainBody/ListCoins";

// Since index.tsx is the main entry and Currencies points to here, main components will be placed here
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ListCoins />
    </div>
  );
}
