import Head from "next/head";
import { ListCoins } from "../components/mainBody/ListCoins";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListCoins />
    </div>
  );
}
